blog_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static 
from django.conf import settings
from blogs import views as BlogsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('category/', include('blogs.urls')),
    path('blogs/search/', BlogsView.search, name='search'),
    path('blogs/<slug:slug>/', BlogsView.blogs, name='blogs' ),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:category_id>/', views.posts_by_category, name = 'posts_by_category'),
]

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # category crud
    path('categories/', views.Categories, name='categories'), 
    path('categories/add/',views.add_category,name='add_category'),
    path('categories/edit/<int:pk>/',views.edit_category,name='edit_category'),
    path('categories/delete/<int:pk>', views.delete_category, name='delete_category'),

    # post crud
    path('posts/', views.posts, name='posts'),
    path('posts/add/', views.add_posts, name='add_posts'),
    path('posts/edit/<int:pk>', views.edit_post, name='edit_post'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from blogs.models import Category,Blog

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class PostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'category', 'featured_image', 'short_description', 'blog_body', 'status', 'is_featured')

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blogs.models import Category,Blog
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm, PostForm
# Create your views here.

@login_required(login_url='login')
def dashboard(request):
    category_count = Category.objects.all().count() 
    blogs_count = Blog.objects.all().count()
    context={
        "category_count": category_count,
        "blogs_count":blogs_count,
    }
    return render(request, 'dashboard/dashboard.html',context)

def Categories(request):
    return render(request, 'dashboard/categories.html')

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:categories')
    form = CategoryForm()
    context ={
        'form':form,
    }
    return render(request, 'dashboard/add_category.html',context )

def edit_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('categories')
    form = CategoryForm(instance=category)
    context = {
        'form':form,
        'category':category,
    }
    return render(request, 'dashboard/edit_category.html', context)

def delete_category(request,pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect('dashboard:categories')

def posts(request):
    posts = Blog.objects.all()
    context = {
        'posts':posts,
    }
    return render(request, 'dashboard/posts.html', context)

def add_posts(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # Let AutoSlugField on the model set the slug on save
            post.save()
            return redirect('dashboard:posts')
    form = PostForm()
    context = {
        'form':form,
    }
    return render(request, 'dashboard/add_post.html', context)

def edit_post(request, pk):
    post = get_object_or_404(Blog, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('dashboard:posts')
   
    form = PostForm(instance=post)
    context = {
        'post':post,
        'form':form,
    }
    return render(request, 'dashboard/edit_posts.html', context)

def delete_post(request, pk):
    post = get_object_or_404(Blog, pk=pk)
    post.delete()
    return render(request, 'dashboard:posts')

templates/dashboard/add_category.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    
    <div class='col-md-9'>
        <h1>Add New Category</h1>

        <form action="{% url 'dashboard:add_category' %}" method='POST' style='width:500px;'>
            {% csrf_token %}
            {{form | crispy}}
            <button type='submit' class='btn btn-warning'>Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/add_post.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    
    <div class='col-md-9'>
        <h1>Add New Blog</h1>

        <form action="{% url 'dashboard:add_posts' %}" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{form | crispy}}
            <button type='submit' class='btn btn-warning'>Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/categories.html
{% extends 'base.html' %}

{%block content %}

<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    
    <div class='col-md-9'>
        <h1>All Categories</h1>
        <a href='{% url 'dashboard:add_category' %}' class='btn btn-dark text-light float-right mb-2'>Add New</a>
        <table class="table table-hover">
  <thead>
    <tr> 
      <th>Category name</th>
      <th>Created At</th> 
      <th>Updated At</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for cat in categories %}
    <tr>
      <td>{{cat}}</td>
      <td>{{cat.created_at}}</td>
      <td>{{cat.updated_at}}</td>
      <td>
        <a href="{% url 'dashboard:edit_category' cat.id %}"><i class="fa fa-edit text-success"></i></a>
        &nbsp;
        <a href="{% url 'dashboard:delete_category' cat.id %}"><i class='fa fa-trash text-danger'></i></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
</div> 


{%endblock%}

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content%}

<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    <div class="col-md-9">
        <span>Logged in as <b>{{user}}</b></span>
        <div class="row">
            
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All CATEGORIES</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{category_count}}</h5></div>
                </div> 
            </div> 
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All POSTS</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{blogs_count}} </h5></div> 
                    </div> 
            </div> 
        </div>
    </div>

</div> 

{% endblock %} 

templates/dashboard/edit_category.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    
    <div class='col-md-9'>
        <h1>Edit Category</h1>

        <form action="" method='POST' style='width:500px;'>
            {% csrf_token %}
            {{form | crispy}}
            <button type='submit' class='btn btn-warning'>Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/edit_posts.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    
    <div class='col-md-9'>
        <h1>Edit Blog</h1>
        
        <form action="{% url 'dashboard:edit_post' post.id %}" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{form | crispy}}
            <button type='submit' class='btn btn-warning'>Submit</button>
        </form>
        
    </div>
</div>

{% endblock %}

templates/dashboard/posts.html
{% extends 'base.html' %}

{%block content %}

<div class='row'>
    
    {% include 'dashboard/sidebar.html'%}
    
    <div class='col-md-9'>
        <h1>All Post</h1>
        <a href='{% url 'dashboard:add_posts' %}' class='btn btn-dark text-light float-right mb-2'>Add New</a>
        <table class="table table-hover">
  <thead>
    <tr> 
      
      <th>Title</th>
      <th>Category</th> 
      <th>Author</th>
      <th>Status</th>
      <th>Feature</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for cat in posts %}
    <tr>
      <td>{{cat.title}}</td>
      <td>{{cat.category}}</td>
      <td>{{cat.author}}</td>
      <td>{{cat.status}}</td>
      <td>{% if cat.is_featured %}<i class='fa fa-check text-success'></i>{% else%}<i class='fa fa-times text-danger'></i>{% endif%}</td>
      <td>
        <a href="{% url 'dashboard:edit_post' cat.id %}"><i class="fa fa-edit text-success"></i></a>
        &nbsp;
        <a href="{% url 'dashboard:delete_category' cat.id %}"><i class='fa fa-trash text-danger'></i></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
</div> 


{%endblock%}

templates/dashboard/sidebar.html
<div class='col-md-3'>
        <div class='nav flex-column nav-pills bg-light' aria-orientation='vertical'>
            <a href="{% url 'dashboard:dashboard' %}" class='nav-link text-dark {% if '/dashboard/' == request.path %}bg-warning{% endif %}'>Dashboard</a>
            <a href="{% url 'dashboard:categories'%}" class='nav-link text-dark {% if '/categories/' in request.path %}bg-warning{% endif %}'>Categories</a>
            <a href="{% url 'dashboard:posts' %}" class='nav-link text-dark {% if '/posts/' in request.path %}bg-warning{% endif %}'>Blogs</a>
            <a href="" class='nav-link text-dark'>Logout</a>
        </div>     
</div>